#!/bin/sh

echo getting image name
image=$(azure vm show "$1"  |
	awk -F'"' '/sourceImageName/ {print $2}')

echo deleting vm "$1"
azure vm delete -q "$1"

echo deleting image "$image"
azure vm image delete -b "$image"
